version: '3'
services:
  postgres:
    container_name: application-postgres
    image: postgres
    ports:
      - "${DOCKER_DB_PORT}:5432"
    environment:
      POSTGRES_PASSWORD: "dbPassword"
      POSTGRES_USER: "dbUser"
    volumes:
      - ./database/initsql/database_init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
  redis:
    container_name: application-redis
    image: redis
    command: >
      --requirepass redisPassword
    environment:
      REDIS_PASSWORD: redisPassword
    ports:
      - "${DOCKER_REDIS_PORT}:6379"
  app:
    container_name: application-server
    image: golang:1.20-alpine
    ports:
      - "${DOCKER_APP_PORT}:80"
    volumes:
      - .:/go/src/app
      - ./upload:/upload
    working_dir: /go/src/app
    command: >
      sh -c "go mod tidy
      && go run cmd/server/main.go"
    depends_on:
      - postgres
      - redis
