version: '3'
services:
  postgres:
    container_name: elotus-postgres
    image: postgres
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_PASSWORD: "elotus"
      POSTGRES_USER: "elotus"
    volumes:
      - ./database_init.sql:/docker-entrypoint-initdb.d/init.sql
      - ../postgres:/var/lib/postgresql/data
    restart: always
  redis:
    container_name: elotus-redis
    image: redis
    environment:
      - REDIS_PASSWORD=elotus
  app:
    container_name: elotus-v1
    image: golang:1.20-alpine
    ports:
      - "${SERVER_PORT}:80"
    volumes:
      - .:/go/src/app
      - ./upload:/upload
    working_dir: /go/src/app
    command: >
      sh -c "go mod tidy
      && go run cmd/server/main.go"
    depends_on:
      - postgres
      - redis
